Crafting/Models/CraftingSystemContext.cs
using Microsoft.EntityFrameworkCore;

namespace Crafting.Models
{
  public class CraftingSystemContext : DbContext
  {
    public DbSet<Item> Items {get; set;}
    public DbSet<Recipe> Recipes {get; set;}
    public DbSet<Ingredient> Ingredients {get; set;}
    public DbSet<Product> Products {get; set;}

    public CraftingSystemContext(DbContextOptions options) : base(options) { }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
      optionsBuilder.UseLazyLoadingProxies();
    }
  }
}

Crafting/Models/DesignTimeDbContextFactory.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Configuration;
using System.IO;

namespace Crafting.Models
{
  public class CraftingSystemContextFactory : IDesignTimeDbContextFactory<CraftingSystemContext>
  {

    CraftingSystemContext IDesignTimeDbContextFactory<CraftingSystemContext>.CreateDbContext(string[] args)
    {
      IConfigurationRoot configuration = new ConfigurationBuilder()
          .SetBasePath(Directory.GetCurrentDirectory())
          .AddJsonFile("appsettings.json")
          .Build();

      var builder = new DbContextOptionsBuilder<CraftingSystemContext>();

      builder.UseMySql(configuration["ConnectionStrings:DefaultConnection"], ServerVersion.AutoDetect(configuration["ConnectionStrings:DefaultConnection"]));

      return new CraftingSystemContext(builder.Options);
    }
  }
}

Crafting/Models/Item.cs
using System.Collections.Generic;

namespace Crafting.Models
{
  public class Item
  {
    public Item()
    {
      this.Ingredients = new HashSet<Ingredient>();
      this.Products = new HashSet<Product>();
    }

    public int ItemId {get; set;}
    public int Quantity {get; set;} = 0;
    public string ItemName {get; set;}
    public virtual ICollection<Ingredient> Ingredients {get;}
    public virtual ICollection<Product> Products {get;}

    public bool CheckQuantity(int quantity)
    {
      return quantity < Quantity;
    }

    public void UseQuantity(int quantity)
    {
      if (CheckQuantity(quantity))
      {
        Quantity -= quantity;
      }
    }

    public void AddQuantity(int quantity)
    {
      Quantity += quantity;
    }
  }
}

Crafting/Models/ItemRecipe.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace Crafting.Models
{  
  public abstract class ItemRecipe
  {
    public int ItemId {get; set;}
    public virtual Item Item {get; set;}
    public int RecipeId { get; set;}
    public virtual Recipe Recipe {get; set;}
  } 

  public class Ingredient : ItemRecipe
  {
    public int IngredientId {get; set;}
  }
  public class Product : ItemRecipe
  {
    public int ProductId {get; set;}
  }
}

Crafting/Models/Recipe.cs
using System.Collections.Generic;

namespace Crafting.Models
{
  public class Recipe
  {
    public Recipe()
    {
      this.Ingredients = new HashSet<Ingredient>();
      this.Products = new HashSet<Product>();
    }

    public int RecipeId {get; set;}
    public string Name {get; set;}
  
    public virtual ICollection<Ingredient> Ingredients {get;}
    public virtual ICollection<Product> Products {get;}
  }
}

Crafting/Controllers/HomeController.cs
using Crafting.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Crafting.Controllers
{
  public class HomeController : Controller
  {
     private readonly CraftingSystemContext _db;
    
    public HomeController(CraftingSystemContext db)
    {
      _db = db;
    }
    [HttpGet("/")]
    public ActionResult Index()
    {
      ViewBag.Inventory = (from item in _db.Items where item.Quantity > 0 select item).ToList();
      ViewBag.Recipes = _db.Recipes
        .Include(recipe => recipe.Ingredients)
        .ThenInclude(ingredient => ingredient.Item)
        .Include(recipe => recipe.Products)
        .ThenInclude(product => product.Item)
        .ToList();
      return View();
    }

    [HttpGet("/LoadRecipe/{id}")]
    public ActionResult LoadRecipe(int id)
    {
      Recipe model = _db.Recipes
        .Include(recipe => recipe.Ingredients)
        .ThenInclude(ingredient => ingredient.Item)
        .Include(recipe => recipe.Products)
        .ThenInclude(product => product.Item)
        .FirstOrDefault(recipe => recipe.RecipeId == id);
      return PartialView("_RecipeDetails", model);
    }
    [HttpPost ("/Craft/{id}")]
    public ActionResult Craft(int id)
    {
      Recipe target = _db.Recipes
        .Include(recipe => recipe.Ingredients)
        .ThenInclude(ingredient => ingredient.Item)
        .Include(recipe => recipe.Products)
        .ThenInclude(product => product.Item)
        .FirstOrDefault(recipe => recipe.RecipeId == id);
      foreach(Ingredient ingredient in target.Ingredients)
      {
        ingredient.Item.UseQuantity(1);
        _db.Entry(ingredient.Item).State = EntityState.Modified;
        _db.SaveChanges();
      }
      foreach(Product product in target.Products)
      {
        product.Item.AddQuantity(1);
        _db.Entry(product.Item).State = EntityState.Modified;
        _db.SaveChanges();
      }      
      return RedirectToAction("Index");
    }
  }
}

Crafting/Controllers/ItemsController.cs
using Crafting.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;

namespace Crafting.Controllers
{
  public class ItemsController : Controller
  {
    private readonly CraftingSystemContext _db;
    
    public ItemsController(CraftingSystemContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      return View(_db.Items.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Item item)
    {
      _db.Items.Add(item);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
      Item model = _db.Items.FirstOrDefault(item => item.ItemId == id);
      return View(model);
    }

    [HttpPost]
    public ActionResult Edit(Item item)
    {
      _db.Entry(item).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

Crafting/Controllers/RecipesController.cs
using Crafting.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace Crafting.Controllers
{
  public class RecipesController : Controller
  {
    private readonly CraftingSystemContext _db;
    
    public RecipesController(CraftingSystemContext db)
    {
      _db = db;
    }
    
    public ActionResult Index()
    {
      return View(_db.Recipes.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.Items = _db.Items.ToList();
      return View();
    }
    
    [HttpPost]
    public ActionResult Create(Recipe recipe, IFormCollection joins)
    {
      _db.Recipes.Add(recipe);
      _db.SaveChanges();
      int temp;
      foreach(var join in joins)
      {
        if(int.TryParse(join.Value, out temp))
        {
          for(int i = 0; i < int.Parse(join.Value); i++)
          {
            string itemId = join.Key.Remove(0, 1);
            if (join.Key[0] == 'I')
            {
              _db.Ingredients.Add(new Ingredient {RecipeId = recipe.RecipeId, ItemId = int.Parse(itemId)});
            }
            else if (join.Key[0] == 'P')
            {
              _db.Products.Add(new Product {RecipeId = recipe.RecipeId, ItemId = int.Parse(itemId)});
            }
          }
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Recipe target = _db.Recipes
        .Include(recipe => recipe.Ingredients)
        .ThenInclude(ingredient => ingredient.Item)
        .Include(recipe => recipe.Products) 
        .ThenInclude(product => product.Item)
        .FirstOrDefault(recipe => recipe.RecipeId == id);
      return View(target);
    }

    // public ActionResult Edit(int id)
    // {
    //   //edit the rId object
    // }
    // [HttpPost]
    // public ActionResult Edit(Recipe recipe)
    // {
    //   //make the change
    // }
  }
}

Crafting/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}
@using Crafting.Models;
@*a list of items where your quantity is greater than 0*@
<h2>Your Inventory</h2>
<ul>
  @foreach(Item item in ViewBag.Inventory)
  {
    <li>@item.ItemName : @item.Quantity</li>
  }
</ul>

@*a dropdown filled with recipes*@
@*a reactive text box that shows the recipe requirements and products*@

<div id="recipe-control-box">
  <form>
    <label>Active Recipe: 
      <select id="active-recipe">
        @foreach(Recipe recipe in ViewBag.Recipes)
        {
          <option Value =@recipe.RecipeId>@recipe.Name</option>
        }
      </select>
    </label>
  </form>

  <div id="recipe-details">
    @Html.Partial("_RecipeDetails")
  </div>

  @*Jquery should dump info here.
    on each ingredient the quantity in inventory/quantity required (could be green if inv>=req else red)

    make button only gets added if you have the required materials.

    get recipe ID from select box, (active-recipe)
    get recipe quantities from database
    get inventory quantities from database
    check to see if inventory quantities are greater than recipe
  *@
</div>

<h1>Welcome Home</h1>
<h3>wanna go somewhere else?</h3>

<script src="~/Scripts/MainCrafting.js"></script>

Crafting/Views/Items/Create.cshtml
@{
  Layout = "_Layout";
}

@model Crafting.Models.Item;

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.ItemName)
    @Html.TextBoxFor(model => model.ItemName, new {@required = "required"})
    <input type="submit" value="Add item" />
}

Crafting/Views/Items/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Crafting.Models.Item;

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.ItemId)
  @Html.LabelFor(model => model.ItemName, "Name:")
  @Html.EditorFor(model => model.ItemName)
  @Html.LabelFor(model => model.Quantity, "Adjust Quantity:")
  @Html.TextBoxFor(model => model.Quantity, new {@type = "number", @Value = Model.Quantity, @min = "0", @step = "1"})
  <input type="submit" value="Submit changes" />
}

Crafting/Views/Items/Index.cshtml
@{
  Layout = "_Layout";
}

@using Crafting.Models;

<h2>List of Items available for crafting:</h2>
<h4><em>(Click an item to edit name and quantity available.)</em></h4>

@if (Model.Count > 0)
{
<ul>
@foreach (Item item in Model)
{
  <li>@Html.ActionLink($"{item.ItemName}", "Edit", new {id = item.ItemId}) <em>Qty: @item.Quantity</em></li>
}
</ul>
}

<p>@Html.ActionLink("Create a new Item", "Create")</p>

Crafting/Views/Recipes/Create.cshtml
@{
  Layout = "_Layout";
}

@using Crafting.Models;
@model Crafting.Models.Recipe;

<h2>Create a New Recipe:</h2>

@Html.Label("Add an item as an ingredient (recipe input) or product (recipe output):")
<select id="item-to-add">
  @foreach(Item item in ViewBag.Items)
  {
    <option value=@item.ItemId>@item.ItemName</option>
  }
</select>
<input id="qty-to-add" type="number" value = "1" min="1" step="1"/>
<button id="ingredient-add" type="button">Add ingredient</button>
<button id="product-add" type="button">Add product</button>

<form id = "main-form" action="Create" method="POST">
    @Html.LabelFor(model => model.Name, "Name the Recipe:")
    @Html.TextBoxFor(model => model.Name, new{@id = "recipe-name"})
    
    <h4>Ingredients:</h4>
    <div id="ingredients"></div>
    <h4>Products</h4>
    <div id="products"></div>

    <input id="final-check-button" type="submit" value="Add recipe" />
</form>

<script src="~/Scripts/RecipeCreate.js"></script>

Crafting/Views/Recipes/Details.cshtml
@{
  Layout = "_Layout";
}

@using Crafting.Models;
@using System.Collections.Generic;

<h3>@Model.Name</h3>

<h4>Ingredients</h4>
<ul>
  @{
    Dictionary<string, int> ingredients = new Dictionary<string, int> {};
    foreach (Ingredient ingredient in Model.Ingredients)
    {
      if (ingredients.ContainsKey(ingredient.Item.ItemName))
      {
        ingredients[ingredient.Item.ItemName] += 1;
      }
      else
      {
        ingredients.Add(ingredient.Item.ItemName, 1);
      }
    }
    foreach (var item in ingredients)
    {
      <li>@item.Key Qty: @item.Value</li>
    }
  }
</ul>
<h4>Products</h4>
<ul>
  @{
    Dictionary<string, int> products = new Dictionary<string, int> {};
    foreach (Product product in Model.Products)
    {
      if (products.ContainsKey(product.Item.ItemName))
      {
        products[product.Item.ItemName] += 1;
      }
      else
      {
        products.Add(product.Item.ItemName, 1);
      }
    }
    foreach (var item in products)
    {
      <li>@item.Key Qty: @item.Value</li>
    }
  }
</ul>

Crafting/Views/Recipes/Index.cshtml
@{
  Layout = "_Layout";
}

@using Crafting.Models;

<h2>List of recipes available for crafting:</h2>
<h4><em>(Click a recipe to edit.)</em></h4>

@if (Model.Count > 0)
{
<ul>
@foreach (Recipe recipe in Model)
{
  <li>@Html.ActionLink($"{recipe.Name}", "Details", new {id = recipe.RecipeId})</li>
}
</ul>
}

<p>@Html.ActionLink("Create a new recipe", "Create")</p>

Crafting/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Crafting System</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <link rel="stylesheet" href="~/css/styles.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
</head>
<body>
  <div class="container">
    @RenderBody()
    <div class="link-bar">
      @Html.ActionLink("Home", "Index", "Home")
      @Html.ActionLink("See Item Index", "Index", "Items")
      @Html.ActionLink("See Recipe Index", "Index", "Recipes")
    </div>
  </div>
</body>
</html>

Crafting/Views/Shared/_RecipeDetails.cshtml
@model Crafting.Models.Recipe;
@using Crafting.Models;

@if (@Model != null)
{
<h4>Ingredients</h4>
<ul>
  @{
    Dictionary<string, int> ingredients = new Dictionary<string, int> {};
    foreach (Ingredient ingredient in Model.Ingredients)
    {
      if (ingredients.ContainsKey(ingredient.Item.ItemName))
      {
        ingredients[ingredient.Item.ItemName] += 1;
      }
      else
      {
        ingredients.Add(ingredient.Item.ItemName, 1);
      }
    }
    foreach (var item in ingredients)
    {
      int inventoryValue=0;
      String target = item.Key;
      @foreach(Ingredient ingredient in Model.Ingredients)
      {
        if(target == ingredient.Item.ItemName)
        {
          inventoryValue = ingredient.Item.Quantity;
        }
      }
      <li>@item.Key : @inventoryValue / @item.Value</li>

    }
  }
</ul>
<h4>Products</h4>
<ul>
  @{
    Dictionary<string, int> products = new Dictionary<string, int> {};
    foreach (Product product in Model.Products)
    {
      if (products.ContainsKey(product.Item.ItemName))
      {
        products[product.Item.ItemName] += 1;
      }
      else
      {
        products.Add(product.Item.ItemName, 1);
      }
    }
    foreach (var item in products)
    {
      <li>@item.Key Qty: @item.Value</li>
    }
  }
</ul>


@*for each ingredient relationship, check to see if the inventory quantity is greater than the recipy requirement*@
bool craftable = true;
@foreach(Ingredient ingredient in Model.Ingredients)
{
  if(ingredient.Item.Quantity < ingredients[ingredient.Item.ItemName])
  {
    craftable = false;
    break;
  }
}
if(craftable)
{
  <form action="Craft/@Model.RecipeId" Method = "POST">
    @* <hidden id = "id" value=@Model.RecipeId> *@
    <button type="submit">Craft</button>
  </form>
}

}